In [2]:
import numpy


In [3]:
import numpy as np
np.random.seed(42)

matrix = np.random.randint(low=0, high=10, size=(4, 4))
print(matrix)


[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]]


In [4]:
import numpy as np

vector1 = np.random.randint(low=0, high=10, size=(4, 1))
vector2 = np.random.randint(low=0, high=10, size=(4, 1))

print("Vector 1:")
print(vector1)

print("Vector 2:")
print(vector2)


Vector 1:
[[1]
 [7]
 [5]
 [1]]
Vector 2:
[[4]
 [0]
 [9]
 [5]]


In [5]:
result1 = np.dot(matrix, vector1)
result2 = np.dot(matrix, vector2)

print("Result 1:")
print(result1)

print("Result 2:")
print(result2)


Result 1:
[[66]
 [85]
 [57]
 [50]]
Result 2:
[[107]
 [ 72]
 [ 90]
 [ 93]]


In [6]:
concatenated_matrix = np.concatenate((vector1, vector2), axis=1)
result = np.dot(matrix, concatenated_matrix)

print("Result:")
print(result)


Result:
[[ 66 107]
 [ 85  72]
 [ 57  90]
 [ 50  93]]
